### PR TITLE
Fix edit category bottom sheet save button logic

### LINKED ISSUE #149: User can't edit category name without editing its image
### Video

https://github.com/user-attachments/assets/d108effc-d144-47a8-bdda-3ca9e5944052

### Notes 

Main focus is with the code handling the save button status.

### PR DESCRIPTION
**Pull request by yusufnasserdev**
Closes #149

### CODE REVIEW

File: app/src/main/java/com/london/tudee/presentation/screens/category/category_details/CategoryDetailsEditBottomSheet.kt [hunk 1]
```diff
@@ -102,9 +102,7 @@ private fun CategoryDetailsEditContent(
     viewModel: CategoryDetailsViewModel = koinViewModel(),
 ) {
     val context = LocalContext.current
-    var categoryName by remember {
-        mutableStateOf(category.titleRes?.let { context.getString(it) } ?: category.title ?: "")
-    }
+    var categoryName by remember { mutableStateOf(category.title ?: "") }
```
Comment (ahmeddsamii) [inline app/src/main/java/com/london/tudee/presentation/screens/category/category_details/CategoryDetailsEditBottomSheet.kt:105]: why did you use the title direct? is this will work with localization? 

var categoryName by remember {
mutableStateOf(category.titleRes?.let { context.getString(it) } ?: category.title ?: "")
}

this was the original code and i think it works with localization

Comment (ahmeddsamii) [reply app/src/main/java/com/london/tudee/presentation/screens/category/category_details/CategoryDetailsEditBottomSheet.kt:105]: i mean that we has two types of categories (predefined and from gallery) for those are predefined it should be translated to arabic and english but in case of from gallery there is no need to be in arabic and english

Comment (yusufnasserdev) [reply app/src/main/java/com/london/tudee/presentation/screens/category/category_details/CategoryDetailsEditBottomSheet.kt:105]: You can't edit a predefined category.

**Review by ahmeddsamii — APPROVED** [review]

**Review by AbdelrhmanAyman20470 — APPROVED** [review]
